package:
  name: optv
  version: 0.2.3

source:
  git_url: https://github.com/OpenPTV/openptv.git

build:
  number: 1
  script: cd py_bind && python setup.py prepare && python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - pyyaml

test:
  requires:
    - nose
  commands:
    - nosetests
  imports:
    - optv

about:
  home: http://www.openptv.net
  license:  LGPL v3.0
  summary: "A library of core algorithms for OpenPTV"
  
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - alexlib
