package:
  name: optv
  version: 0.2.3

source:
  git_url: https://github.com/OpenPTV/openptv.git
  git_tag: master  # I didn't bother to tag the repo, so just pretend 'master' is version 0.1.0

build:
  number: 0
  script: cd ../py_bind 
  script: python setup.py prepare 
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython
    - pyyaml

test:
  requires:
    - nose
  commands:
    - nosetests
  imports:
    - optv

about:
  home: http://www.openptv.net
  license:  LGPL v3.0
  summary: "A library of core algorithms for OpenPTV"
  
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - alexlib
