{% set version = "0.2.4" %}

package:
  name: optv
  version: {{ version }} 

source:
  url: https://github.com/OpenPTV/openptv/archive/{{ version }}.tar.gz
  sha256: 4cafc70d966f2694cc936973eb2581d35bdffd6ec4b30f9ff99a1515c07f4042

build:
  number: 0
  skip: True  # [not py3k]
  script:
  - cd py_bind
  - {{ PYTHON }} setup.py prepare
  - {{ PYTHON }} setup.py install
  
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy 1.16.1
    - cython
    - pyyaml
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyyaml

test:
  source_files:
    - py_bind/test
  requires:
    - nose
  commands: 
    - cd py_bind/test
    - nosetests 
  imports:
    - optv

about:
  home: http://www.openptv.net
  license:  LGPL v3.0
  summary: "A library of core algorithms for OpenPTV"
  license_file: COPYING.LESSER
  
extra:
  recipe-maintainers:
    - alexlib
    
