package:
  name: optv
  version: 0.2.3

source:
  url: https://github.com/OpenPTV/openptv/archive/0.2.3.tar.gz
  sha256: 21b8709dedc8696ff454d83d2d6af582252dbd9cf621f5d78ecdd64ce0af48cb

build:
  number: 0
  script: cd py_bind && python setup.py prepare && python setup.py install
  
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pyyaml
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - matplotlib
    - scipy

test:
  requires:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - matplotlib
    - scipy
    - nose
  commands:
    - nosetests
  imports:
    - optv

about:
  home: http://www.openptv.net
  license:  LGPL v3.0
  summary: "A library of core algorithms for OpenPTV"
  license_file: COPYING.LESSER
  
extra:
  recipe-maintainers:
    - alexlib
    
