package:
  name: liboptv
  version: 0.0.1

source:
  git_url: https://github.com/OpenPTV/openptv.git
  git_tag: master  # I didn't bother to tag the repo, so just pretend 'master' is version 0.1.0

requirements:
  build:
    - cmake
    - check

  run:
    - cmake

build:

  # already linked relative to $ORIGIN, so we need to turn
  # off conda's relocation mechanism because it screws it up
  binary_relocation: false

about:
  home: https://github.com/OpenPTV/openptv.git
  license:  LGPL v3.0
